name: good_place_camp
description: Good Place Camp Site & App.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
      
  get:

  table_calendar:

  flutter_localizations: 
    sdk: flutter

  jiffy:

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
dependency_overrides:
  intl: ^0.15.8

flutter:
  uses-material-design: true
  assets:
      - assets/