name: good_place_camp
description: Good Place Camp Site & App.

version: 1.0.0+1

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences:
      
  get:

  table_calendar:

  url_launcher:

  flutter_inappwebview:

  google_maps_flutter:

  flutter_localizations: 
    sdk: flutter

  cupertino_icons: ^0.1.2

  flutter_brand_icons:

  crypto: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
      - assets/