name: good_place_camp
description: 매번 업데이트 되는 명당 캠핑장 자리 정보를 받아보세요!

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter 

  shared_preferences:
      
  get:

  table_calendar:

  url_launcher:

  flutter_inappwebview:

  google_maps_flutter:

  firebase_core: "^0.7.0"
  firebase_auth: "^0.20.1"
  google_sign_in: "^4.5.1"
  flutter_facebook_auth: "^1.0.0"
  sign_in_with_apple:

  cupertino_icons: ^0.1.2

  flutter_brand_icons:

  crypto: ^3.0.0

  flutter_inapp_purchase:

dependency_overrides:
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
      - assets/